### ISSUE TITLE
不起作用，是dylib的路径不对了吗

### ISSUE THREAD

**Issue by ynot16** [mademao/MDMMainThreadChecker#1]
dlopen之后返回的handle是null

**Comment by ynot16** [comment]
"dlopen(/Developer/usr/lib/libMainThreadChecker.dylib, 0x0002): tried: '/usr/lib/system/introspection/libMainThreadChecker.dylib' (no such file), '/Developer/usr/lib/libMainThreadChecker.dylib' (no such file)

**Comment by mademao** [comment]
这边没有发现你所说问题，可以具体提供一下开发环境和调试设备型号么

**Comment by ynot16** [comment]
> 

Xcode Version 13.4.1 (13F100)
MacOS Monterey
iPhone XSMAX 
iOS15.6

**Comment by mademao** [comment]
libMainThreadChecker.dylib位置改变，问题已解决~

**Comment by mademao** [comment]
[365f46a](https://github.com/mademao/MDMMainThreadChecker/commit/365f46aa0ecb335ec69e1f5499bb0651c0a4f7d6)

**Comment by ynot16** [comment]
> 

可以了，感谢。顺带请教下，是怎么找到dylib的位置的呢？

**Comment by ynot16** [comment]
你有在项目使用过吗
我这边拖进项目使用，发现重定向输出不起作用。遇到项目调用NSLog的地方会直接卡死在writev函数上

**Comment by mademao** [comment]
> > 
> 
> 可以了，感谢。顺带请教下，是怎么找到dylib的位置的呢？

连接真机随意进入一个项目调试，在控制台使用 image list 可以看到所有被加载镜像的路径，通过这些信息可以得到系统库位置

**Comment by mademao** [comment]
> 你有在项目使用过吗 我这边拖进项目使用，发现重定向输出不起作用。遇到项目调用NSLog的地方会直接卡死在writev函数上

没有遇到你所说的问题，可以贴一个卡死时的调用栈看看
